server:
  port: 9001

spring:
  application:
    name: example
  boot:
    admin:
      client:
        url: http://localhost:9000
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Dxw314159
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/webapp
    suffix: .ftl

management:
  endpoints:
    web:
      exposure:
        include: '*'